### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by CodeProKid** [dfmedia/DFM-Transients#6]
Self explanatory. Test all the things!

**Comment by jasonbahl** [comment]
@CodeProKid I think this should probably move up to be highest priority. I think good tests will help make sure the shape of the code stays well organized and ensure that future changes don't break anything unintentionally

**Comment by CodeProKid** [comment]
@jasonbahl yeah I totally agree. I have a few small things that I've added to the 1.1.1 milestone that I'll probably ship first, but this is the next thing to get done. I've created a milestone for 1.2.0, and this issue will act as kind of an epic for it. I'm going to crete a new branch for messing around with unit tests, and then I'll start breaking out issues for specific tests.
